apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.name" . }}-postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ include "postgres.password" . | b64enc | quote }}
  postgres-username: {{ .Values.postgres.username | b64enc | quote }}
  postgres-name: {{ .Values.postgres.name | b64enc | quote }}
