package iq.earthlink.social.classes.enumeration;

public enum PostEventType {
    POST_COMMENT_ADDED,
    POST_COMMENT_REMOVED,
    POST_UPVOTE_ADDED,
    POST_DOWNVOTE_ADDED,
    POST_UPVOTE_REMOVED,
    POST_DOWNVOTE_REMOVED,
    POST_COMMENT_UPVOTE_ADDED,
    POST_COMMENT_DOWNVOTE_ADDED,
    POST_COMMENT_UPVOTE_REMOVED,
    POST_COMMENT_DOWNVOTE_REMOVED,
    POST_AUTHOR_DISPLAY_NAME_UPDATED,
    PURGE_STATS,
    POST_COUNT_UPDATED
}

