scrape_configs:
  - job_name: 'Social Media APP input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8083', 'host.docker.internal:8084', 'host.docker.internal:8085', 'host.docker.internal:8086', 'host.docker.internal:8093', 'host.docker.internal:8094']
        labels:
          application: 'Social Media APP'