FROM public.ecr.aws/docker/library/openjdk:17-jdk-slim AS runtime
ARG service

WORKDIR /app
# Copy the jar file from the build stage
# COPY --from=build /app/build/libs/*.jar ./app.jar
COPY ${service}/service/build/libs/${service}-0.0.1.jar /app/app.jar

# Expose the application's port
EXPOSE 8080

# Run the application
CMD ["java", "-Xmx512M", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]