server:
  port: ${PORT:8088}
  auth:
    apiAuthHeader: X-API-KEY
    apiSecretKey: ${API_SECRET_KEY:secret}
    secret: ${SECRET_KEY:EkQCe8jwME187iyzqpxNPUlwu9MaMkXY}
openapi:
  shortVideoService:
    base-path: /api/v1/
management:
  health:
    rabbit:
      enabled: false
spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: short-video-service
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:250MB}
      max-file-size: ${MAX_FILE_SIZE:250MB}
  main:
    allow-bean-definition-overriding: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:guest}
    database: ${REDIS_DB:0}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jackson:
    serialization:
      write_dates_as_timestamps: true

filestorage:
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    externalEndpoint: ${MINIO_EXTERNAL_ENDPOINT:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY:minio}
    secretKey: ${MINIO_SECRET_KEY:password}
    bucketName: ${MINIO_BUCKET:social-media-short-videos}

short-video-registry:
  service:
    url: ${SHORT_VIDEO_REGISTRY_SERVICE_URL:http://localhost:8092}

comment:
  service:
    url: ${COMMENT_SERVICE_URL:http://localhost:8097}

person:
  service:
    url: ${PERSON_SERVICE_URL:http://localhost:8081}

sentry:
  dsn: ${SENTRY_DSN:https://5807e19a3a2943f6862270d23262508f@o4505390493073408.ingest.sentry.io/4505390512340992}
  environment: ${SENTRY_ENVIRONMENT:local}