server:
  port: ${PORT:8086}
  auth:
    secret: ${SECRET_KEY:EkQCe8jwME187iyzqpxNPUlwu9MaMkXY}
    apiAuthHeader: X-API-KEY
    apiSecretKey: ${API_SECRET_KEY:secret}
spring:
  redis:
    host: ${REDIS_STRUCT_HOST:localhost}
    port: ${REDIS_STRUCT_PORT:6379}
    password: ${REDIS_STRUCT_PASS:guest}
    database: ${REDIS_DB:0}
    cluster:
      nodes: ${REDIS_STRUCT_ClUSTER_NODES:173.18.0.2:6379,173.18.0.3:6379,173.18.0.4:6379}
    mode: ${REDIS_MODE:standalone}
  datasource:
    enabled: false
social:
  mode: ${APP_MODE:recentMode}
management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true

sentry:
  dsn: ${SENTRY_DSN:https://5807e19a3a2943f6862270d23262508f@o4505390493073408.ingest.sentry.io/4505390512340992}
  environment: ${SENTRY_ENVIRONMENT:local}