apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "post-service.fullname" . }}
  labels:
    {{- include "post-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "post-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-config.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "post-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "post-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.30.1
          command: ['sh', '-c', 'until nc -zv {{ .Release.Name }}-post-service-postgres 5432 -w1; do echo waiting for {{ .Release.Name }}-post-service-postgres; sleep 5; done;']
        - name: wait-for-rabbit
          image: busybox:1.30.1
          command: ['sh', '-c', 'until nc -zv {{ .Release.Name }}-rabbit-svc 5672 -w1; do echo waiting for {{ .Release.Name }}-rabbitmq; sleep 5; done;']
        - name: wait-for-person
          image: busybox:1.30.1
          command: ['sh', '-c', 'until nc -zv {{ .Release.Name }}-person-service 8080 -w1; do echo waiting for {{ .Release.Name }}-person-service; sleep 5; done;']
        - name: wait-for-group
          image: busybox:1.30.1
          command: ['sh', '-c', 'until nc -zv {{ .Release.Name }}-group-service 8080 -w1; do echo waiting for {{ .Release.Name }}-group-service; sleep 5; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.name }}-post-service-env-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
